default: &default
  adapter: postgresql
  encoding: unicode
  database: dbill
  host: localhost
  pool: 5

development:
  <<: *default

test:
  <<: *default
  database: dbill_test

production:
  adapter: postgresql
  encoding: unicode
  database: dbill_production
  pool: 5